"""add ml_models table

Revision ID: 298a13e4581a
Revises: d13891ec8827
Create Date: 2026-02-28 14:05:59.089010

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298a13e4581a'
down_revision: Union[str, None] = 'd13891ec8827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_blob', sa.LargeBinary(), nullable=False),
    sa.Column('model_format', sa.String(length=20), nullable=False),
    sa.Column('model_size_bytes', sa.Integer(), nullable=False),
    sa.Column('model_hash', sa.String(length=64), nullable=False),
    sa.Column('training_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_data_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True),
    sa.Column('eval_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type', 'version', name='uq_ml_model_type_version')
    )
    op.create_index('ix_ml_model_active', 'ml_models', ['model_type', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_model_active', table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
