"""add_simulation_tables

Revision ID: 91e4f2ba54e6
Revises: be8c6f1d19d2
Create Date: 2026-02-25 23:58:06.661427

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91e4f2ba54e6'
down_revision: Union[str, None] = 'be8c6f1d19d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_memory_agent_type', 'agent_memories', ['agent_name', 'memory_type'], unique=False)
    op.create_index('ix_agent_memory_confidence', 'agent_memories', ['confidence'], unique=False)
    op.create_table('paper_portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('total_pnl_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('simulated_theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('thesis_text', sa.Text(), nullable=False),
    sa.Column('entry_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_horizon_days', sa.Integer(), nullable=True),
    sa.Column('expected_catalysts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position_sizing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('generation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_thesis_id', sa.Integer(), nullable=True),
    sa.Column('ticker_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retirement_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_thesis_id'], ['simulated_theses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sim_thesis_generated_by', 'simulated_theses', ['generated_by'], unique=False)
    op.create_index('ix_sim_thesis_status', 'simulated_theses', ['status'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('monte_carlo_p_value', sa.Float(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['simulated_theses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_thesis_ran', 'backtest_runs', ['thesis_id', 'ran_at'], unique=False)
    op.create_table('deep_hedging_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('model_blob', sa.LargeBinary(), nullable=True),
    sa.Column('training_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_loss', sa.Float(), nullable=True),
    sa.Column('validation_loss', sa.Float(), nullable=True),
    sa.Column('hedging_error', sa.Float(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heston_calibrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('v0', sa.Float(), nullable=False),
    sa.Column('kappa', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('sigma_v', sa.Float(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('market_iv_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'as_of', name='uq_heston_cal_ticker_date')
    )
    op.create_index('ix_heston_cal_ticker_date', 'heston_calibrations', ['ticker_id', 'as_of'], unique=False)
    op.create_table('options_chain',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('call_put', sa.String(length=4), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('implied_vol', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_options_chain_fetched', 'options_chain', ['fetched_at'], unique=False)
    op.create_index('ix_options_chain_ticker_exp_strike', 'options_chain', ['ticker_id', 'expiration', 'strike'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesis_id'], ['simulated_theses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_pos_portfolio_status', 'paper_positions', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_paper_pos_thesis', 'paper_positions', ['thesis_id'], unique=False)
    op.create_table('simulation_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['simulated_theses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sim_log_event_type', 'simulation_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_sim_log_thesis_created', 'simulation_logs', ['thesis_id', 'created_at'], unique=False)
    op.create_table('vol_surfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('surface_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'as_of', 'model_type', name='uq_vol_surface_ticker_date_model')
    )
    op.create_index('ix_vol_surface_ticker_date', 'vol_surfaces', ['ticker_id', 'as_of'], unique=False)
    op.alter_column('filings', 'is_parsed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('filings', 'is_analyzed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_filings_is_analyzed', table_name='filings', postgresql_where='(is_analyzed IS FALSE)')
    op.drop_index('ix_filings_is_parsed', table_name='filings', postgresql_where='(is_parsed IS FALSE)')
    op.drop_index('ix_filings_raw_text_hash', table_name='filings')
    op.drop_index('ix_insider_trades_ticker_txn_date', table_name='insider_trades')
    op.create_index(op.f('ix_insider_trades_filed_date'), 'insider_trades', ['filed_date'], unique=False)
    op.drop_index('ix_institutional_cik_period', table_name='institutional_holdings')
    op.alter_column('news_articles', 'source_tier',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_news_content_hash', table_name='news_articles')
    op.drop_constraint('news_articles_raw_content_hash_key', 'news_articles', type_='unique')
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_raw_content_hash'), 'news_articles', ['raw_content_hash'], unique=True)
    op.alter_column('price_bars', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('theses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickers', 'in_sp500',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickers', 'in_custom',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickers', 'in_watchlist',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('tickers_symbol_key', 'tickers', type_='unique')
    op.drop_index('ix_tickers_symbol', table_name='tickers')
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.create_index('ix_tickers_symbol', 'tickers', ['symbol'], unique=False)
    op.create_unique_constraint('tickers_symbol_key', 'tickers', ['symbol'])
    op.alter_column('tickers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tickers', 'in_watchlist',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tickers', 'in_custom',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tickers', 'in_sp500',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('theses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('price_bars', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'yfinance'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_news_articles_raw_content_hash'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.create_unique_constraint('news_articles_raw_content_hash_key', 'news_articles', ['raw_content_hash'])
    op.create_index('ix_news_content_hash', 'news_articles', ['raw_content_hash'], unique=False)
    op.alter_column('news_articles', 'source_tier',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.create_index('ix_institutional_cik_period', 'institutional_holdings', ['institution_cik', 'period_date'], unique=False)
    op.drop_index(op.f('ix_insider_trades_filed_date'), table_name='insider_trades')
    op.create_index('ix_insider_trades_ticker_txn_date', 'insider_trades', ['ticker_id', 'transaction_date'], unique=False)
    op.create_index('ix_filings_raw_text_hash', 'filings', ['raw_text_hash'], unique=False)
    op.create_index('ix_filings_is_parsed', 'filings', ['is_parsed'], unique=False, postgresql_where='(is_parsed IS FALSE)')
    op.create_index('ix_filings_is_analyzed', 'filings', ['is_analyzed'], unique=False, postgresql_where='(is_analyzed IS FALSE)')
    op.alter_column('filings', 'is_analyzed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('filings', 'is_parsed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index('ix_vol_surface_ticker_date', table_name='vol_surfaces')
    op.drop_table('vol_surfaces')
    op.drop_index('ix_sim_log_thesis_created', table_name='simulation_logs')
    op.drop_index('ix_sim_log_event_type', table_name='simulation_logs')
    op.drop_table('simulation_logs')
    op.drop_index('ix_paper_pos_thesis', table_name='paper_positions')
    op.drop_index('ix_paper_pos_portfolio_status', table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index('ix_options_chain_ticker_exp_strike', table_name='options_chain')
    op.drop_index('ix_options_chain_fetched', table_name='options_chain')
    op.drop_table('options_chain')
    op.drop_index('ix_heston_cal_ticker_date', table_name='heston_calibrations')
    op.drop_table('heston_calibrations')
    op.drop_table('deep_hedging_models')
    op.drop_index('ix_backtest_thesis_ran', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('ix_sim_thesis_status', table_name='simulated_theses')
    op.drop_index('ix_sim_thesis_generated_by', table_name='simulated_theses')
    op.drop_table('simulated_theses')
    op.drop_table('paper_portfolios')
    op.drop_index('ix_agent_memory_confidence', table_name='agent_memories')
    op.drop_index('ix_agent_memory_agent_type', table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
